spring.application.name=collabnote-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/collabnote
spring.datasource.username=disinisanujana
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true